package Clientes;


/**
* Clientes/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Clientes.idl
* jueves 18 de octubre de 2018 22H51' COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
