package Clientes;


/**
* Clientes/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Clientes.idl
* miércoles 7 de noviembre de 2018 20H54' COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (String nombre, String apellido, int empresa_ruc);
  boolean actualizarCliente (int id_cliente, String nombre, String apellido, int empresa_ruc);
  boolean eliminarCliente (int id_cliente);
  String consultarCliente (int id_cliente);
  void shoutdown ();
} // interface ClienteOperations
