package Clientes;


/**
* Clientes/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Clientes.idl
* jueves 18 de octubre de 2018 22H51' COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (String nombre, String apellido, String empresa_ruc);
  boolean actualizarCliente (int id_cliente, String nombre, String apellido, String empresa_ruc);
  boolean eliminarCliente (int id_cliente);
  String consultarCliente (int id_cliente);
  void shoutdown ();
} // interface ClienteOperations
