package Clientes;


/**
* Clientes/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Clientes.idl
* miércoles 7 de noviembre de 2018 20H54' COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
