package Comprobante_De_Venta;


/**
* Comprobante_De_Venta/ComprobanteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 9 de noviembre de 2018 00H19' COT
*/

public interface ComprobanteOperations 
{
  boolean insertarComprobante (String fecha, int codigo_cliente, int cliente_id_cliente, int producto_id_prod);
  boolean actualizarComprobante (int id_comprobante, int codigo_cliente, String fecha, int cliente_id_cliente, int producto_id_prod);
  boolean eliminarComprobante (int id_comprobante);
  String consultarComprobante (int id_comprobante);
  void shoutdown ();
} // interface ComprobanteOperations
