package Comprobante_De_Venta;


/**
* Comprobante_De_Venta/Comprobante.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 9 de noviembre de 2018 00H19' COT
*/

public interface Comprobante extends ComprobanteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Comprobante
