package Productos;


/**
* Productos/ProductoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* viernes 19 de octubre de 2018 16H20' COT
*/

public interface ProductoOperations 
{
  boolean insertarProducto (String nombre, String modelo, String marca, float precio_compra, float precio_venta);
  boolean actualizarProducto (int id_prod, String nombre, String modelo, String marca, float precio_compra, float precio_venta);
  boolean eliminarProducto (int id_prod);
  String consultarProducto (int id_prod);
  void shoutdown ();
} // interface ProductoOperations
