package Productos;

/**
* Productos/ProductoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* viernes 19 de octubre de 2018 16H20' COT
*/

public final class ProductoHolder implements org.omg.CORBA.portable.Streamable
{
  public Productos.Producto value = null;

  public ProductoHolder ()
  {
  }

  public ProductoHolder (Productos.Producto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Productos.ProductoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Productos.ProductoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Productos.ProductoHelper.type ();
  }

}
