package Productos;


/**
* Productos/Producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* viernes 19 de octubre de 2018 16H20' COT
*/

public interface Producto extends ProductoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Producto
