package Empleados;


/**
* Empleados/_EmpleadoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* viernes 19 de octubre de 2018 16H07' COT
*/

public class _EmpleadoStub extends org.omg.CORBA.portable.ObjectImpl implements Empleados.Empleado
{

  public boolean insertarEmpleado (String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, double hora_entrada, double hora_salida, String telefono, float sueldo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarEmpleado", true);
                $out.write_wstring (nombre);
                $out.write_wstring (apellido);
                $out.write_wstring (genero);
                $out.write_wstring (direccion);
                $out.write_wstring (fecha_nacimiento);
                $out.write_wstring (estado_civil);
                $out.write_wstring (codigo_cargo);
                $out.write_double (hora_entrada);
                $out.write_double (hora_salida);
                $out.write_wstring (telefono);
                $out.write_float (sueldo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarEmpleado (nombre, apellido, genero, direccion, fecha_nacimiento, estado_civil, codigo_cargo, hora_entrada, hora_salida, telefono, sueldo        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarEmpleado

  public boolean actualizarEmpleado (int cedula_empleado, String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, double hora_entrada, double hora_salida, String telefono, float sueldo, int empresa_ruc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarEmpleado", true);
                $out.write_long (cedula_empleado);
                $out.write_wstring (nombre);
                $out.write_wstring (apellido);
                $out.write_wstring (genero);
                $out.write_wstring (direccion);
                $out.write_wstring (fecha_nacimiento);
                $out.write_wstring (estado_civil);
                $out.write_wstring (codigo_cargo);
                $out.write_double (hora_entrada);
                $out.write_double (hora_salida);
                $out.write_wstring (telefono);
                $out.write_float (sueldo);
                $out.write_long (empresa_ruc);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarEmpleado (cedula_empleado, nombre, apellido, genero, direccion, fecha_nacimiento, estado_civil, codigo_cargo, hora_entrada, hora_salida, telefono, sueldo, empresa_ruc        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarEmpleado

  public boolean eliminarEmpleado (int cedula_empleado, int empresa_ruc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarEmpleado", true);
                $out.write_long (cedula_empleado);
                $out.write_long (empresa_ruc);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarEmpleado (cedula_empleado, empresa_ruc        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarEmpleado

  public String consultarEmpleado (int cedula_empleado, int empresa_ruc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarEmpleado", true);
                $out.write_long (cedula_empleado);
                $out.write_long (empresa_ruc);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarEmpleado (cedula_empleado, empresa_ruc        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarEmpleado

  public void shoutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shoutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shoutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shoutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Empleados/Empleado:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EmpleadoStub
