package Empleados;


/**
* Empleados/EmpleadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* martes 23 de octubre de 2018 15H26' COT
*/

public interface EmpleadoOperations 
{
  boolean insertarEmpleado (String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, String hora_entrada, String hora_salida, String telefono, float sueldo);
  boolean actualizarEmpleado (int cedula_empleado, String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, double hora_entrada, double hora_salida, String telefono, float sueldo, int empresa_ruc);
  boolean eliminarEmpleado (int cedula_empleado, int empresa_ruc);
  String consultarEmpleado (int cedula_empleado, int empresa_ruc);
  void shoutdown ();
} // interface EmpleadoOperations
