package Empleados;


/**
* Empleados/Empleado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* viernes 19 de octubre de 2018 16H07' COT
*/

public interface Empleado extends EmpleadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empleado
