package Empleados;


/**
* Empleados/Empleado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* martes 13 de noviembre de 2018 16H06' COT
*/

public interface Empleado extends EmpleadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empleado
