package Empleados;

/**
* Empleados/EmpleadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* martes 23 de octubre de 2018 15H26' COT
*/

public final class EmpleadoHolder implements org.omg.CORBA.portable.Streamable
{
  public Empleados.Empleado value = null;

  public EmpleadoHolder ()
  {
  }

  public EmpleadoHolder (Empleados.Empleado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Empleados.EmpleadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Empleados.EmpleadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Empleados.EmpleadoHelper.type ();
  }

}
