package Empleados;


/**
* Empleados/Empleado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* martes 23 de octubre de 2018 15H26' COT
*/

public interface Empleado extends EmpleadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empleado
