package Empleados;


/**
* Empleados/EmpleadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* martes 13 de noviembre de 2018 16H06' COT
*/

public interface EmpleadoOperations 
{
  boolean insertarEmpleado (int cedula_empleado, String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, String hora_entrada, String hora_salida, String telefono, float sueldo, int empresa_ruc);
  boolean actualizarEmpleado (int cedula_empleado, String nombre, String apellido, String genero, String direccion, String fecha_nacimiento, String estado_civil, String codigo_cargo, String hora_entrada, String hora_salida, String telefono, float sueldo, int empresa_ruc);
  boolean eliminarEmpleado (int cedula_empleado);
  String consultarEmpleado (int cedula_empleado);
  void shoutdown ();
} // interface EmpleadoOperations
