package Comprobante_De_Pago;


/**
* Comprobante_De_Pago/ComprobanteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 19 de octubre de 2018 15H00' COT
*/

abstract public class ComprobanteHelper
{
  private static String  _id = "IDL:Comprobante_De_Pago/Comprobante:1.0";

  public static void insert (org.omg.CORBA.Any a, Comprobante_De_Pago.Comprobante that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Comprobante_De_Pago.Comprobante extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Comprobante_De_Pago.ComprobanteHelper.id (), "Comprobante");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Comprobante_De_Pago.Comprobante read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ComprobanteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Comprobante_De_Pago.Comprobante value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Comprobante_De_Pago.Comprobante narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Comprobante_De_Pago.Comprobante)
      return (Comprobante_De_Pago.Comprobante)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Comprobante_De_Pago._ComprobanteStub stub = new Comprobante_De_Pago._ComprobanteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Comprobante_De_Pago.Comprobante unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Comprobante_De_Pago.Comprobante)
      return (Comprobante_De_Pago.Comprobante)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Comprobante_De_Pago._ComprobanteStub stub = new Comprobante_De_Pago._ComprobanteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
