package Comprobante_De_Pago;

/**
* Comprobante_De_Pago/ComprobanteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 19 de octubre de 2018 15H00' COT
*/

public final class ComprobanteHolder implements org.omg.CORBA.portable.Streamable
{
  public Comprobante_De_Pago.Comprobante value = null;

  public ComprobanteHolder ()
  {
  }

  public ComprobanteHolder (Comprobante_De_Pago.Comprobante initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Comprobante_De_Pago.ComprobanteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Comprobante_De_Pago.ComprobanteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Comprobante_De_Pago.ComprobanteHelper.type ();
  }

}
