package Comprobante_De_Pago;


/**
* Comprobante_De_Pago/ComprobantePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 19 de octubre de 2018 15H00' COT
*/

public abstract class ComprobantePOA extends org.omg.PortableServer.Servant
 implements Comprobante_De_Pago.ComprobanteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarComprobante", new java.lang.Integer (0));
    _methods.put ("actualizarComprobante", new java.lang.Integer (1));
    _methods.put ("eliminarComprobante", new java.lang.Integer (2));
    _methods.put ("consultarComprobante", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Comprobante_De_Pago/Comprobante/insertarComprobante
       {
         String fecha = in.read_wstring ();
         int codigo_cliente = in.read_long ();
         boolean $result = false;
         $result = this.insertarComprobante (fecha, codigo_cliente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Comprobante_De_Pago/Comprobante/actualizarComprobante
       {
         int id_comprobante = in.read_long ();
         int codigo_cliente = in.read_long ();
         String fecha = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarComprobante (id_comprobante, codigo_cliente, fecha);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Comprobante_De_Pago/Comprobante/eliminarComprobante
       {
         int id_comprobante = in.read_long ();
         boolean $result = false;
         $result = this.eliminarComprobante (id_comprobante);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Comprobante_De_Pago/Comprobante/consultarComprobante
       {
         int id_comprobante = in.read_long ();
         String $result = null;
         $result = this.consultarComprobante (id_comprobante);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Comprobante_De_Pago/Comprobante/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Comprobante_De_Pago/Comprobante:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Comprobante _this() 
  {
    return ComprobanteHelper.narrow(
    super._this_object());
  }

  public Comprobante _this(org.omg.CORBA.ORB orb) 
  {
    return ComprobanteHelper.narrow(
    super._this_object(orb));
  }


} // class ComprobantePOA
