package Comprobante_De_Pago;


/**
* Comprobante_De_Pago/ComprobanteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 19 de octubre de 2018 15H00' COT
*/

public interface ComprobanteOperations 
{
  boolean insertarComprobante (String fecha, int codigo_cliente);
  boolean actualizarComprobante (int id_comprobante, int codigo_cliente, String fecha);
  boolean eliminarComprobante (int id_comprobante);
  String consultarComprobante (int id_comprobante);
  void shoutdown ();
} // interface ComprobanteOperations
