package Comprobante_De_Pago;


/**
* Comprobante_De_Pago/Comprobante.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comprobantes.idl
* viernes 19 de octubre de 2018 15H00' COT
*/

public interface Comprobante extends ComprobanteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Comprobante
