
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIEGO
 */
public class Comprobante_De_Venta extends javax.swing.JFrame {
    public int indice;   
    private DefaultTableModel modeloTablaComp;

    /** Creates new form Comprobante_De_Pago */
    public Comprobante_De_Venta() {
        initComponents();            
       cargarTablaComp();
        ComboBoxCli cbc = new ComboBoxCli();
      DefaultComboBoxModel modeloCli = new DefaultComboBoxModel(cbc.mostrarClis());
       cmbCli.setModel(modeloCli);
        
        ComboBoxProd cbp = new ComboBoxProd();
        DefaultComboBoxModel modeloProd = new DefaultComboBoxModel(cbp.mostrarBoxProds());
        cmbProd.setModel(modeloProd);
    }
    
    
     private void getColumn() {
        modeloTablaComp = (DefaultTableModel) tblComprobante.getModel();
         
         modeloTablaComp.addColumn("ID");
         modeloTablaComp.addColumn("fecha");
         modeloTablaComp.addColumn("codigo_Cliente");
         modeloTablaComp.addColumn("Cliente_id");
         modeloTablaComp.addColumn("Producto_id");

    }

    //Metodo par cargar tabla
    
    //Metodo par cargar tabla
    private void cargarTablaComp(){
     Comprobante ObjComprobante = new Comprobante();
        ResultSet result = ObjComprobante.cargarComprobante();
        try {
            //creamos un arreglo de 3 sectores
            Object Datos [] = new Object[5];
            while (result.next()) {
                for (int i = 0; i <5; i++) {
                    Datos[i]=result.getObject(i+1) ;
                }
                modeloTablaComp.addRow(Datos);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCli = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbProd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComprobante = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("id comprovante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Codigo Cliente ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("Cliente ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        getContentPane().add(cmbCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("COMPROBANTE DE PAGO ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(cmbProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setText("Fecha ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        txtId.setText("0");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 150, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 40));

        btnConsultar.setBackground(new java.awt.Color(51, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar ");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, 40));

        btnGuardar.setBackground(new java.awt.Color(51, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar ");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 40));

        btnLimpiar.setBackground(new java.awt.Color(51, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 40));

        btnNext.setBackground(new java.awt.Color(51, 255, 255));
        btnNext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 120, 40));

        tblComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprobanteMouseClicked(evt);
            }
        });
        tblComprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblComprobanteKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblComprobante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 290, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/32.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        // Elimino el registro del JTable y la tabla cliente
        // Defino el modelo para el JTable
        DefaultTableModel modelo = (DefaultTableModel) tblComprobante.getModel();

        // Asigno el indice del elemento seleccionado
        indice = tblComprobante.getSelectedRow();

        // Asigno a idCiudad el elemento a eliminar
        int id_comprobante = Integer.parseInt(txtId.getText());


        // Elimino el registro del JTable
        modelo.removeRow(indice);

        Comprobante objComprobante = new Comprobante();
        // Elimino el registro de la tabla cliente

        try {

            boolean resultado = objComprobante.eliminarComprobante(id_comprobante);
            // Imprimo el mensaje para indicar si se eliminó o no el registro
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "El registro se elimino.");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR: No se elimino el registro.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        modeloTablaComp = (DefaultTableModel) tblComprobante.getModel();
        modeloTablaComp.setColumnCount(0);
        modeloTablaComp.setRowCount(0);
        getColumn();
        cargarTablaComp();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //LIMPIAR clientes
        modeloTablaComp = (DefaultTableModel) tblComprobante.getModel();

        // Limpio los campos
        // *** Limpio los Campos ***
        txtId.setText("0");
        txtFecha.setText("");
        
        cmbCli.setSelectedIndex(0);
        cmbProd.setSelectedIndex(0);
        txtCodigoCliente.requestFocus();
        modeloTablaComp.setColumnCount(0);
        modeloTablaComp.setRowCount(0);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        if (txtFecha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su fecha ");
            txtFecha.requestFocus();
            return;

        }
        if (txtCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su comprobante ");
            txtCodigoCliente.requestFocus();
            return;

        }
        if (cmbCli.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "selecione una empresa  ");
            cmbCli.requestFocus();
            return;
        }

        Comprobante objComprobante = new Comprobante();

        ComboBoxCli cbc  =  (ComboBoxCli) cmbCli.getSelectedItem();
        ComboBoxProd cbp =  (ComboBoxProd) cmbProd.getSelectedItem();
       

        String fecha = txtFecha.getText();
        int id_comprobante = Integer.parseInt(txtId.getText());
        int cliente_id_cliente = cbc.getId();
        int producto_id_prod = cbp.getId();
        int codigo_cliente = Integer.parseInt(txtCodigoCliente.getText());
       
        try {
            
            if (id_comprobante == 0) {
                boolean resultado = objComprobante.insertarComprobante(fecha, codigo_cliente, cliente_id_cliente, producto_id_prod);
                if (resultado == true) {
                    JOptionPane.showMessageDialog(null, "Se inserto un nuevo registro.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al insertar.");
                }
            }
            else {
                boolean resultado = objComprobante.actualizarComprobante(id_comprobante, codigo_cliente, fecha, cliente_id_cliente, producto_id_prod);
                if (resultado == true) {
                    JOptionPane.showMessageDialog(null, "Se actualizó el registro.");
                    cargarTablaComp();
                }
                 else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar.");
                    //Empresa obj = new Empresa();
                }   //obj.setVisible(true);
            
            }
           
                
                
            // *** Limpio los Campos ***
            txtId.setText("0");
        txtFecha.setText("");
        
        cmbCli.setSelectedIndex(0);
        cmbProd.setSelectedIndex(0);
        txtCodigoCliente.requestFocus();
        modeloTablaComp.setColumnCount(0);
        modeloTablaComp.setRowCount(0);


        } catch (Exception e) {
               System.out.println("error..................");
                
        }
            
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
        txtFecha.transferFocus();
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
        txtCodigoCliente.transferFocus();
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void tblComprobanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblComprobanteKeyTyped
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_tblComprobanteKeyTyped

    private void tblComprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprobanteMouseClicked
        // TODO add your handling code here:
         int seleccion = tblComprobante.rowAtPoint(evt.getPoint());
        txtId.setText(String.valueOf(tblComprobante.getValueAt(seleccion, 0)));
        txtFecha.setText(String.valueOf(tblComprobante.getValueAt(seleccion, 1)));
        txtCodigoCliente.setText(String.valueOf(tblComprobante.getValueAt(seleccion, 2)));
       //  txtsetText(String.valueOf(tblComprobante.getValueAt(seleccion, 2)));
         
    }//GEN-LAST:event_tblComprobanteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprobante_De_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbCli;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComprobante;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
