
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIEGO
 */
public class Comprobante_De_Venta extends javax.swing.JFrame {
    public int indice;   
    private DefaultTableModel modeloTablaComp;

    /** Creates new form Comprobante_De_Pago */
    public Comprobante_De_Venta() {
        initComponents();            
       cargarTablaComp();
//        ComboBoxCli cbCli = new ComboBoxCli();
//        DefaultComboBoxModel modeloCmbCli = new DefaultComboBoxModel(cbCli.mostrarBoxClis());
//        cmbCli.setModel(modeloCmbCli);
//        
//        ComboBoxProd cbProd = new ComboBoxProd();
//        DefaultComboBoxModel modeloCmbProd = new DefaultComboBoxModel(cbProd.mostrarBoxProds());
//        cmbProd.setModel(modeloCmbProd);
    }
    
    
    private String[] getColumn(){
        String columnas[] = new String[]{"id","Fecha","codigo_Cliente","cliente","Producto"};
        return columnas;
    }
    //Metodo par cargar tabla
    private void cargarTablaComp(){
     Comprobante ObjComprobante = new Comprobante();
        ResultSet result = ObjComprobante.cargarComprobante();
        try {
            //creamos un arreglo de 3 sectores
            Object Datos [] = new Object[4];
            while (result.next()) {
                for (int i = 0; i <4; i++) {
                    Datos[i]=result.getObject(i+1) ;
                }
                modeloTablaComp.addRow(Datos);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbCli = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbProd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("id comprovante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Codigo Cliente ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        btnConsultar.setBackground(new java.awt.Color(51, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar ");
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(51, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar ");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        btnNext.setBackground(new java.awt.Color(51, 255, 255));
        btnNext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNext.setText("NEXT");
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("Cliente ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        getContentPane().add(cmbCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("COMPROBANTE DE PAGO ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(cmbProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setText("Fecha ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        txtId.setText("0");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 150, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, 300));

        tblComp.setModel(modeloTablaComp);
        jScrollPane1.setViewportView(tblComp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 370, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
if (txtFecha.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Digite una fecha dd/mm/aaaa ");
           txtFecha.requestFocus();
           return;
           
       }
       if (txtCodigoCliente.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Digite un codigo ");
           txtCodigoCliente.requestFocus();
           return;
        
       }
       if (cmbCli.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(null,"selecione un cliente  ");
           cmbCli.requestFocus();
           return;
       } 
       
       
        Comprobante objComprobante = new Comprobante();
        String fecha = txtFecha.getText();
        String codigo_clinete = txtCodigoCliente.getText();
         int cliente_id_cliente = cmbCli.getSelectedIndex();
        int id_comprobante = Integer.parseInt(txtId.getText());
      
        if( id_comprobante == 0){
            boolean resultado = objComprobante.insertarComprobante(fecha, cliente_id_cliente, cliente_id_cliente, PROPERTIES);
            if(resultado == true){
                JOptionPane.showMessageDialog(null, "Se inserto un nuevo registro.");
                 modeloTablaComp.setNumRows(0);
                cargarTablaComp();
            }else{
                JOptionPane.showMessageDialog(null, "Error al insertar.");
            }
            
        }else{
            boolean resultado = objComprobante.actualizarComprobante(id_comprobante, cliente_id_cliente, fecha, cliente_id_cliente, PROPERTIES);
            if(resultado == true){
                JOptionPane.showMessageDialog(null, "Se actualizó el registro.");
                cargarTablaComp();
            }else{
                JOptionPane.showMessageDialog(null, "Error al actualizar.");
                 //Empresa obj = new Empresa();
                //obj.setVisible(true);
            }
         // *** Limpio los Campos ***      
        txtId.setText("0");
        txtCodigoCliente.setText("");
        txtFecha.setText("");
        cmbCli.setSelectedIndex(0);
        txtFecha.requestFocus();
        cmbProd.setSelectedIndex(0);
        }        
             // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprobante_De_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprobante_De_Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbCli;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComp;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
