module Empleados{
    interface Empleado{
    boolean insertarEmpleado(in long cedula_empleado,in wstring nombre, in wstring apellido, in  wstring genero,in  wstring direccion,in wstring fecha_nacimiento,in  wstring estado_civil,in  wstring codigo_cargo,in wstring hora_entrada,in wstring hora_salida, in wstring telefono, in float sueldo,in long empresa_ruc);
    boolean actualizarEmpleado(in long cedula_empleado, in wstring nombre, in wstring apellido, in  wstring genero,in  wstring direccion,in wstring fecha_nacimiento,in  wstring estado_civil,in  wstring codigo_cargo,in wstring hora_entrada,in wstring hora_salida, in wstring telefono, in float sueldo, in long empresa_ruc);
    boolean eliminarEmpleado(in long cedula_empleado);
    wstring consultarEmpleado(in long cedula_empleado);
    oneway void shoutdown();
    };
    
};

