import java.sql.ResultSet;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class Proveedor extends javax.swing.JFrame {
    public int indice;  
    private DefaultTableModel modeloTablaProveedor;

   
    /**/public Proveedor() {
        
         modeloTablaProveedor = new DefaultTableModel(null,getColumn());
         this.setLocationRelativeTo(null);
        initComponents();
        cargarTablaproveedor();
    }
    private String[] getColumn(){
        String columnas[] = new String[]{"ruc","Nombre","direccion","telefono"};
        return columnas;
    }
    //Metodo par cargar tabla
    private void cargarTablaproveedor(){
     Proveedores ObjproProveedor = new Proveedores();
        ResultSet result = ObjproProveedor.cargarProveedor();
        try {
            //creamos un arreglo de 3 sectores
            Object Datos [] = new Object[4];
            while (result.next()) {
                for (int i = 0; i <4; i++) {
                    Datos[i]=result.getObject(i+1) ;
                }
                modeloTablaProveedor.addRow(Datos);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtRucProve = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Proveedor ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 300, 52);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 83, 26);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Direccion ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 110, 26);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 94, 26);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(200, 110, 120, 20);

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(200, 140, 120, 20);

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(200, 170, 120, 20);

        btnConsultar.setBackground(new java.awt.Color(51, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar ");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(120, 310, 150, 35);

        btnGuardar.setBackground(new java.awt.Color(51, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(10, 310, 119, 35);

        btnLimpiar.setBackground(new java.awt.Color(51, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar ");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(270, 310, 120, 35);

        btnEliminar.setBackground(new java.awt.Color(51, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(390, 310, 121, 35);

        btnNext.setBackground(new java.awt.Color(51, 255, 255));
        btnNext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNext.setText("NEXT");
        getContentPane().add(btnNext);
        btnNext.setBounds(520, 310, 100, 35);

        tblProveedor.setModel(modeloTablaProveedor);
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 50, 270, 190);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("RUC PROVEDOR ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 70, 190, 26);
        getContentPane().add(txtRucProve);
        txtRucProve.setBounds(200, 80, 120, 20);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 640, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         // Elimino el registro del JTable y la tabla proveedor

        // Defino el modelo para el JTable
        DefaultTableModel modelo = (DefaultTableModel) tblProveedor.getModel();
        
        
        // Asigno el indice del elemento seleccionado
        indice = tblProveedor.getSelectedRow();

        // Asigno a idCiudad el elemento a eliminar
        int ruc_prov = Integer.parseInt(txtRucProve.getText());;

        // Elimino el registro del JTable
        modelo.removeRow(indice);
        
        Proveedores objProveedor = new Proveedores();
         // Elimino el registro de la tabla proveedor
         boolean resultado = objProveedor.eliminarProveedor(ruc_prov);
        // Imprimo el mensaje para indicar si se eliminó o no el registro
        if(resultado == true){
            JOptionPane.showMessageDialog(null, "El registro se elimino.");
        }
        else{
            JOptionPane.showMessageDialog(null, "ERROR: No se elimino el registro.");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
          Proveedores objProveedores = new Proveedores();
        JOptionPane.showMessageDialog(null, objProveedores.consultarProveedor(1));
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) tblProveedor.getModel();
         
        // Limpio los campos
         // *** Limpio los Campos ***      
        txtRucProve.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombre.requestFocus();
        
       
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

         if (txtNombre.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Digite Su nombtr ");
           txtNombre.requestFocus();
           return;
           
       }
       if (txtDireccion.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Digite Su direccion ");
           txtDireccion.requestFocus();
           return;
        
       }
        if (txtTelefono.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Digite Su telefono ");
           txtTelefono.requestFocus();
           return;
        
       }


        // TODO add your handling code here:
        Proveedores objProveedor = new Proveedores();
        String nombres = txtNombre.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        
        int ruc = Integer.parseInt(txtRucProve.getText());
        if (ruc==0) {
            
        
        boolean resultado = objProveedor.insertarProveedor(nombres, direccion, telefono);
        if (resultado== true) {
            JOptionPane.showMessageDialog(null, "Se inserto un nuevo registro");
            modeloTablaProveedor.setNumRows(0); 
            cargarTablaproveedor();
        }else{
            JOptionPane.showMessageDialog(null, "Erro al inserta su datos ");
            }
        }else{
            boolean resultado = objProveedor.actualizarProveedor(ruc, nombres, direccion, telefono);
            if (resultado== true) {
            JOptionPane.showMessageDialog(null, "Se actualizo el registro");
            //cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar  ");
            }
        } 
         // *** Limpio los Campos ***  
        txtRucProve.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        
        
         char  validar = evt.getKeyChar();
    if(Character.isDigit(validar)){
        getToolkit().beep();
        evt.consume();

        JOptionPane.showMessageDialog(rootPane,"Ingresa tu nombre proveedor");
}

        
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume(); {
        
        }      
        
         char validar=evt.getKeyChar();
    if(Character.isLetter(validar)){
    getToolkit().beep();
    evt.consume();
    JOptionPane.showMessageDialog(rootPane,"Ingrensar su numero proveedor ");
        }
        
        
        
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        // TODO add your handling code here:
        
        int seleccion = tblProveedor.rowAtPoint(evt.getPoint());
        txtNombre.setText(String.valueOf(tblProveedor.getValueAt(seleccion,0)));
        txtDireccion.setText(String.valueOf(tblProveedor.getValueAt(seleccion,1)));
        txtTelefono.setText(String.valueOf(tblProveedor.getValueAt(seleccion,2)));
    }//GEN-LAST:event_tblProveedorMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
          txtNombre.transferFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
          txtDireccion.transferFocus();
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
          txtTelefono.transferFocus();
    }//GEN-LAST:event_txtTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRucProve;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
