
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DIEGO
 */
public class Prov extends javax.swing.JFrame {
    
    public int indice;    
    private DefaultTableModel modeloTablaProv;
    
    public Prov() {
     
        
        initComponents();
        
        ComboBoxRues cb = new ComboBoxRues();
        DefaultComboBoxModel modeloRuesProv = new DefaultComboBoxModel(cb.mostrarRues());
        cmbEmpresa.setModel(modeloRuesProv);
    }

    private void getColumn() {
        modeloTablaProv = (DefaultTableModel) tblProv.getModel();
         
         modeloTablaProv.addColumn("ID");
         modeloTablaProv.addColumn("Nombre");
         modeloTablaProv.addColumn("Direccion");
         modeloTablaProv.addColumn("Telefono");
         modeloTablaProv.addColumn("Empresa_Ruc");

    }

    //Metodo par cargar tabla
    private void cargarTablaproveedor() {
        Proveedores ObjproProveedor = new Proveedores();
        ResultSet result = ObjproProveedor.cargarProveedor();
        try {
            //creamos un arreglo de 3 sectores
            Object Datos[] = new Object[5];
            while (result.next()) {
                for (int i = 0; i < 5; i++) {
                    Datos[i] = result.getObject(i + 1);
                }
                modeloTablaProv.addRow(Datos);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProvRuc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProv = new javax.swing.JTable();
        cmbEmpresa = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Proveedor Ruc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 167, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 253, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Empresa Ruc");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, -1, -1));

        txtProvRuc.setEditable(false);
        txtProvRuc.setText("0");
        getContentPane().add(txtProvRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 115, 89, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 161, 89, -1));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 207, 89, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 253, 89, -1));

        tblProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProv);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 22, 375, 303));

        getContentPane().add(cmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 299, 89, -1));

        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, -1, -1));

        btnConsultar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 343, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 343, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 343, -1, -1));

        btnNext.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 0, 0));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/91134-OIW11W-632.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Elimino el registro del JTable y la tabla proveedor

        // Defino el modelo para el JTable
        DefaultTableModel modelo = (DefaultTableModel) tblProv.getModel();

        // Asigno el indice del elemento seleccionado
        indice = tblProv.getSelectedRow();

        // Asigno a idCiudad el elemento a eliminar
        int ruc_prov = Integer.parseInt(txtProvRuc.getText());;

        // Elimino el registro del JTable
        modelo.removeRow(indice);
        
        Proveedores objProveedor = new Proveedores();
        // Elimino el registro de la tabla proveedor
        boolean resultado = objProveedor.eliminarProveedor(ruc_prov);
        // Imprimo el mensaje para indicar si se eliminó o no el registro
        if (resultado == true) {
            JOptionPane.showMessageDialog(null, "El registro se elimino.");
        } else {
            JOptionPane.showMessageDialog(null, "ERROR: No se elimino el registro.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblProv.getModel();

        // Limpio los campos
        // *** Limpio los Campos ***      
        txtProvRuc.setText("0");
        txtNombre.setText("");
        txtDireccion.setText("");
        cmbEmpresa.setSelectedIndex(0);
        txtNombre.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su nombtr ");
            txtNombre.requestFocus();
            return;
            
        }
        if (txtDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su direccion ");
            txtDireccion.requestFocus();
            return;
            
        }
        if (txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su telefono ");
            txtTelefono.requestFocus();
            return;
            
        }
        if (cmbEmpresa.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Su telefono ");
            cmbEmpresa.requestFocus();
            return;
        }
        // TODO add your handling code here:
        Proveedores objProveedor = new Proveedores();
        
        ComboBoxRues cb =  (ComboBoxRues) cmbEmpresa.getSelectedItem();
        
        String nombres = txtNombre.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        int empresa_ruc = cb.getId();
        
        int ruc_prov = Integer.parseInt(txtProvRuc.getText());
        if (ruc_prov == 0) {
            
            boolean resultado = objProveedor.insertarProveedor(nombres, direccion, telefono, empresa_ruc);
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "Se inserto un nuevo registro");
                
            } else {
                JOptionPane.showMessageDialog(null, "Erro al inserta su datos ");
            }
        } else {
            boolean resultado = objProveedor.actualizarProveedor(ruc_prov, nombres, direccion, telefono, empresa_ruc);
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "Se actualizo el registro");
                //cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar  ");
            }
        }
        // *** Limpio los Campos ***  
        txtProvRuc.setText("0");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombre.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProvMouseClicked
        int seleccion = tblProv.rowAtPoint(evt.getPoint());
       
        txtProvRuc.setText(String.valueOf(tblProv.getValueAt(seleccion, 0)));
        txtNombre.setText(String.valueOf(tblProv.getValueAt(seleccion, 1)));
        txtDireccion.setText(String.valueOf(tblProv.getValueAt(seleccion, 2)));
        txtTelefono.setText(String.valueOf(tblProv.getValueAt(seleccion, 3)));
        // cbmEmpresa.getString(String.valueOf(tblProveedor.getValueAt(seleccion,3)));        // TODO add your handling code here:
    }//GEN-LAST:event_tblProvMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        //LIMPIAR clientes
        modeloTablaProv = (DefaultTableModel) tblProv.getModel();

      
        modeloTablaProv.setColumnCount(0);
        modeloTablaProv.setRowCount(0);
        
        
        getColumn();
        cargarTablaproveedor();     // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProv;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProvRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
