package Empresa;


/**
* Empresa/EmpresasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* jueves 25 de octubre de 2018 12H40' COT
*/

public interface EmpresasOperations 
{
  boolean insertarEmpresas (int ruc, String nombre, String direccion, String telefono, String propietario);
  boolean actualizarEmpresas (int ruc, String nombre, String apellido, String telefono, String propietario);
  boolean eliminarEmpresas (int ruc);
  String consultarEmpresas (int ruc);
  void shoutdown ();
} // interface EmpresasOperations
