package Empresa;


/**
* Empresa/EmpresasHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* jueves 25 de octubre de 2018 12H40' COT
*/

abstract public class EmpresasHelper
{
  private static String  _id = "IDL:Empresa/Empresas:1.0";

  public static void insert (org.omg.CORBA.Any a, Empresa.Empresas that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Empresa.Empresas extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Empresa.EmpresasHelper.id (), "Empresas");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Empresa.Empresas read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EmpresasStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Empresa.Empresas value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Empresa.Empresas narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Empresa.Empresas)
      return (Empresa.Empresas)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Empresa._EmpresasStub stub = new Empresa._EmpresasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Empresa.Empresas unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Empresa.Empresas)
      return (Empresa.Empresas)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Empresa._EmpresasStub stub = new Empresa._EmpresasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
