package Empresa;


/**
* Empresa/Empresas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* viernes 19 de octubre de 2018 15H28' COT
*/

public interface Empresas extends EmpresasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empresas
