package Empresa;


/**
* Empresa/EmpresasPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empresa.idl
* martes 23 de octubre de 2018 15H26' COT
*/

public abstract class EmpresasPOA extends org.omg.PortableServer.Servant
 implements Empresa.EmpresasOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEmpresas", new java.lang.Integer (0));
    _methods.put ("actualizarEmpresas", new java.lang.Integer (1));
    _methods.put ("eliminarEmpresas", new java.lang.Integer (2));
    _methods.put ("consultarEmpresas", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Empresa/Empresas/insertarEmpresas
       {
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         String propietario = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarEmpresas (nombre, direccion, telefono, propietario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Empresa/Empresas/actualizarEmpresas
       {
         int ruc = in.read_long ();
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         String propietario = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarEmpresas (ruc, nombre, apellido, telefono, propietario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Empresa/Empresas/eliminarEmpresas
       {
         int ruc = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEmpresas (ruc);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Empresa/Empresas/consultarEmpresas
       {
         int ruc = in.read_long ();
         String $result = null;
         $result = this.consultarEmpresas (ruc);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Empresa/Empresas/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Empresa/Empresas:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Empresas _this() 
  {
    return EmpresasHelper.narrow(
    super._this_object());
  }

  public Empresas _this(org.omg.CORBA.ORB orb) 
  {
    return EmpresasHelper.narrow(
    super._this_object(orb));
  }


} // class EmpresasPOA
