package Proveedores;


/**
* Proveedores/ProveedorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* viernes 19 de octubre de 2018 15H40' COT
*/

public interface ProveedorOperations 
{
  boolean insertarProveedor (String nombre, String direccion, String telefono);
  boolean actualizarProveedor (int ruc_prov, String nombre, String direccion, String telefono);
  boolean eliminarProveedor (int ruc_prov);
  String consultarProveedor (int ruc_prov);
  void shoutdown ();
} // interface ProveedorOperations
