package Proveedores;


/**
* Proveedores/Proveedor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* sábado 10 de noviembre de 2018 08H57' COT
*/

public interface Proveedor extends ProveedorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedor
