package Proveedores;


/**
* Proveedores/Proveedor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* viernes 19 de octubre de 2018 15H40' COT
*/

public interface Proveedor extends ProveedorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedor
